name = "blog"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/"
not_found_handling = "404-page"

[vars]
NODE_VERSION = "20.0.0"
PNPM_VERSION = "9.14.4"
